logging:
  level:
    org.springframework: INFO
    com.mesofi: DEBUG

    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      database: saintseiyauniverse
