character:
  keyword-exclude:
  - Bandai
  - Myth
  - Cloth
  - Saint

logging:
  level:
    org.springframework: INFO
    com.mesofi: DEBUG

spring:
  data:
    mongodb:
      database: saintseiyauniverse
