logging:
  level:
    org.springframework: INFO
    com.mesofi: DEBUG

server:
  servlet:
    context-path: /api

characters:
  naming-exclusions:
    - Bandai
    - Saint
    - Seiya
    - Myth
    - Cloth
    - Masami
    - Kurumada
    - Cross
    - Correction
    - BOX
    - Modification
    - No
    - Japan
    - version
    - ver.
    - ver
    - OF
    - "-"
    - /
    - gold
    - Tamashi
    - Tamashii
    - Spirits
    - Nation
    - used
    - web
    - Zodiac
    - copyright
    - sticker
    - from
    - figure
    - action
    - with
    - item
    - first
    - bonus
    - product
